name: HiantPlugin
version: ${version}
main: org.insilicon.hiantplugin.HiantPlugin
api-version: '1.21'
authors: ["Prorickey", "LukeIThink", "ModdedKid"]
dependencies:
  server:
    Skript:
      load: BEFORE
      required: true
      join-classpath: true
    LibertyBans:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    CrazyCrates:
      load: BEFORE
      required: true
      join-classpath: true