name: hiantsys
version: '${version}'
main: org.insilicon.hiantsys.Hiantsys
api-version: '1.20'
depend: [LuckPerms, PremiumVanish, PlaceholderAPI]
authors: ["Prorickey", "LukeIThink", "ModdedKid"]
commands:
  hiantsys:
    description: hiantsys
    usage: /hiantsys [argument]
    aliases: [hs]
    permission: hiantsys.admin
