name: hiantsys
version: '${version}'
main: org.insilicon.hiantsys.Hiantsys
api-version: '1.20'
commands:
  hiantsys:
    description: hiantsys
    usage: /hiantsys [argument]
    aliases: [hs]
    permission: hiantsys.admin
