name: HiantPlugin
version: '${version}'
main: org.insilicon.hiantplugin.HiantPlugin
api-version: '1.20'
depend:
  - Skript
  - LibertyBans
  - LuckPerms
  - PremiumVanish
  - PlaceholderAPI
authors: ["Prorickey", "LukeIThink", "ModdedKid"]